### ISSUE TITLE
Programatic usage

### ISSUE THREAD

**Issue by fresheneesz** [liriliri/eustia#1]
It would be great if you could extract the core functionality and release it as a separate module that can be used programatically (by this and other projects). In particular, I'm very interested in using this in conjunction with webpack, where even tho you can pick and choose modules to include, you may use only a small fraction of a module's functionality. I would love to be able to create a webpack plugin using eustia functionality to optimize my bundles to remove all the module functionality my application doesn't use.

**Comment by surunzi** [comment]
The tool itself is already a bundler. However, unlike webpack, it's designed specifically to handle small code snippets only, which makes it much simpler to use. You can use it along with webpack and there is no conflicts between them. Check this project to see how they work together:  https://github.com/liriliri/eruda
